### ISSUE TITLE
How do you compile this as an apk on Github...

### ISSUE THREAD

**Issue by xadamxk** [RBWare/FireTVReboot#1]
I'm a bit new to Android and Github, and have no idea how to compile this app as a raw .apk from Github. Let alone if its even possible.... Halp :(

**Comment by RBWare** [comment]
You can't compile directly from GitHub. If you'd like I can do a tagged release and provide a 1.0 apk for github. I have since moved away from using a FireTV, so I haven't really been maintaining this.

**Comment by xadamxk** [comment]
That would be greatly appreciated, thank you.

**Comment by RBWare** [comment]
If you check the "releases" tab, there is now a 1.0 release, including an APK. Be warned, it was signed with the default android release key.
